[build]
  base = "frontend"  # Set base directory to 'frontend' if your React app is inside the 'frontend' folder
  publish = "frontend/build"  # Path to your React frontend build folder
  functions = "netlify/functions"  # Path to your Netlify functions directory

[build.environment]
  NODE_VERSION = "14"  # Specify Node version (optional)

[build.command]
  command = "npm run build"  # The command to build your React app
